easy_admin:
    entities:

        Service:
            class: App\Entity\Service
            label: services.title
            controller: App\Admin\AdminServiceController
            list:
                fields:
                    - id
                    - title
                    - slug
                    - description
                    - price
                    - language
            form:
                fields:
                    - title
                    - description
                    - { property: price, help: services.price.help }
                    - property: duration
                      type_options:
                          required: false
                    - property: durationUnit
                      type: choice
                      type_options:
                          expanded: true
                          choices: !php/const App\Entity\Service::DURATION_UNITS
                    - language
                    - property: language
                      type: choice
                      type_options:
                          expanded: true
                          choices: !php/const App\Entity\Service::LANGUAGES
                    - property: previous
