root:
    path: /
    controller: App\Controller\RootController
    methods: 'GET'

home:
    path:
        fr: /fr
        en: /en
    controller: App\Controller\HomeController
    methods: 'GET'
    requirements:
        _locale: '%locales_regex%'

contact:
    path:
        fr: /fr/contact
        en: /en/contact
    controller: App\Controller\ContactController
    methods: ['GET', 'POST']
    requirements:
        _locale: '%locales_regex%'

trainings:
    path:
        fr: /fr/formations
        en: /en/trainings
    controller: App\Controller\TrainingsController
    methods: 'GET'
