root:
    path: /
    controller: App\Controller\RootController
    methods: 'GET'

home:
    path: /{_locale}
    controller: App\Controller\HomeController
    methods: 'GET'
    requirements:
        _locale: '%locales_regex%'

contact:
    path: /{_locale}/contact
    controller: App\Controller\ContactController
    methods: ['GET', 'POST']
    requirements:
        _locale: '%locales_regex%'

login:
    path: /{_locale}/login
    methods: 'GET'
    requirements:
        _locale: '%locales_regex%'

logout:
    path: /{_locale}/logout
    methods: 'GET'
    requirements:
        _locale: '%locales_regex%'
