export default [
	{
		"title": "talks.rust_php.title",
		"videos": ["https://www.youtube.com/watch?v=oKkILL8ypIw"],
		"slides": ["https://talks.pierstoval.com/rust-for-php-devs"],
		"lang": "🇫🇷",
		"conference": "Asynconf",
		"date": "2020-12-22",
	},
	{
		"title": "talks.afup_day_2019.atypical",
		"videos": [],
		"slides": ["https://talks.pierstoval.com/neuroatypie-et-it/"],
		"lang": "🇫🇷",
		"conference": "AFUP Day 2019",
		"date": "2019-05-17",
	},
	{
		"title": "talks.nomad_php.esteren_maps",
		"videos": ["https://nomadphp.com/video/232/building-interactive-maps-with-php-and-javascript"],
		"slides": ["https://talks.pierstoval.com/nomad_php_esteren_maps/", ],
		"lang": "🇬🇧",
		"conference": "Nomad PHP",
		"date": "2019-04-11",
	},
	{
		"title": "talks.sf4_news.title",
		"videos": ["https://www.youtube.com/watch?v=F7OmBoqHcfY&t=1739s"],
		"slides": ["http://prezgame.herokuapp.com/presentation"],
		"lang": "🇫🇷",
		"conference": "Meetup PHP TheCamp",
		"date": "2018-02-28",
	},
	{
		"title": "talks.sf3_review.title",
		"videos": [],
		"slides": ["https://talks.pierstoval.com/sfreview"],
		"lang": "🇫🇷",
		"conference": "Meetup PHP HighCo",
		"date": "2017-05-16",
	},
];
