export default [
	{
		"title": "talks.api_platform_con.svelte",
		"videos": ["https://www.youtube.com/watch?v=vFZFYkpyT9w"],
		"slides": ["https://talks.pierstoval.com/api-platform-svelte-and-maximum-buzzwords/"],
		"lang": "🇫🇷",
		"conference": "API Platform Conference 2023",
		"date": "2023-09-22",
	},
	{
		"title": "talks.asynconf.deterministic_code",
		"videos": ["https://www.youtube.com/watch?v=z2H3tbPx8PM"],
		"slides": [],
		"lang": "🇫🇷",
		"conference": "Asynconf 2021",
		"date": "2021-11-01",
	},
	{
		"title": "talks.hello_worlds.title",
		"videos": ["https://www.youtube.com/watch?v=J-et1iPnp9I"],
		"slides": [],
		"lang": "🇫🇷",
		"conference": "AFUP Day 2021 Tours",
		"date": "2021-06-11",
	},
	{
		"title": "talks.rust_php.title",
		"videos": ["https://www.youtube.com/watch?v=oKkILL8ypIw"],
		"slides": ["https://talks.pierstoval.com/rust-for-php-devs"],
		"lang": "🇫🇷",
		"conference": "Asynconf 2020",
		"date": "2020-12-22",
	},
	{
		"title": "talks.afup_forum_php_2019.atypical",
		"videos": ["https://www.youtube.com/watch?v=lBC-AV-o73k"],
		"slides": ["https://talks.pierstoval.com/forum-php-neuroatypie-et-it/#/"],
		"lang": "🇫🇷",
		"conference": "Forum PHP 2019",
		"date": "2019-10-24",
	},
	{
		"title": "talks.afup_day_2019.atypical",
		"videos": [],
		"slides": ["https://talks.pierstoval.com/neuroatypie-et-it/"],
		"lang": "🇫🇷",
		"conference": "AFUP Day 2019",
		"date": "2019-05-17",
	},
	{
		"title": "talks.nomad_php.esteren_maps",
		"videos": ["https://nomadphp.com/video/232/building-interactive-maps-with-php-and-javascript"],
		"slides": ["https://talks.pierstoval.com/nomad_php_esteren_maps/", ],
		"lang": "🇬🇧",
		"conference": "Nomad PHP",
		"date": "2019-04-11",
	},
	{
		"title": "talks.symfonylive.lightning_talk",
		"videos": ["https://symfonycasts.com/screencast/paris2019/lightning-talks"],
		"slides": [],
		"lang": "🇫🇷",
		"conference": "SymfonyLive Paris 2019",
		"date": "2019-03-29",
	},
	{
		"title": "talks.sf4_news.title",
		"videos": ["https://www.youtube.com/watch?v=F7OmBoqHcfY&t=1570s"],
		"slides": ["http://prezgame.herokuapp.com/presentation"],
		"lang": "🇫🇷",
		"conference": "Meetup PHP TheCamp",
		"date": "2018-02-28",
	},
	{
		"title": "talks.sf3_review.title",
		"videos": [],
		"slides": ["https://talks.pierstoval.com/sfreview"],
		"lang": "🇫🇷",
		"conference": "Meetup PHP HighCo",
		"date": "2017-05-16",
	},
];
